spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialectddl-auto=create
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
